### ISSUE TITLE
Adding CSS and starting work on the other pages

### ISSUE THREAD

**Issue by HSEshan** [23460542/CITS3403_GroupProject#2]
One of the next step is to prepare the CSS sheet. Some styles we will add:
`.link-dark {text-decoration: none;}`
`.text-gray {color: gray;}`
Some suitable fonts.

I think this should give us enough of a backbone for the next pages.

**Comment by ash-6666** [comment]
i agree and lets keep the colors simple black and white it will give an elegant look

**Comment by HSEshan** [comment]
This was completed today. Closing.
